#!/bin/bash
# Script para guardar el sitio estático generado en la rama gh-pages
git checkout master
mkdocs serve &
git add .
git commit -m "`date`"
git push origin master
git checkout gh-pages
git checkout master -- site
git add site
cp -a site/* .
git add .
git commit -m "`date`"
echo "Guardando cambios en la rama gh-pages"
git push origin gh-pages
 

