# Información general
site_name: 'Redes con software libre'
site_description: 'Redes de datos con software libre'
site_author: 'Raul Jesus Lopez'
site_url: http://www.rauljesus.xyz/redes

# Repositorio
repo_name: 'Ver en GitHub'
repo_url: 'https://github.com/la9una/redes'

# Copyright
#copyright: '2017 - Raul Jesus Lopez'

# Tema
theme: null
theme_dir: 'themes/material'

# Opciones
extra:
  palette:
    primary: 'indigo'
    accent: 'indigo'
#font:
#    text: 'Roboto'
#    code: 'Roboto Mono'
  social:
#    - type: 'github'
#      link: 'https://github.com/la9una'
    - type: 'twitter'
      link: 'https://twitter.com/la9una'
#    - type: 'linkedin'
#      link: 'https://de.linkedin.com/in/john-doe'
#    - type: 'facebook'
#      link: 'https://www.facebook.com/rauljesuslopez'
  disqus: 'rauljesus-xyz'

# Google Analytics
#google_analytics:
#  - 'UA-98408177-1'
#  - 'auto'

# Extensions
markdown_extensions:
  - pymdownx.arithmatex
  - admonition
#  - codehilite(guess_lang=false,linenums=true)
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - footnotes
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

# Extras
#extra_javascript:
#  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

# Páginas
pages: 
- Inicio: 'index.md'
- SSH: 
    - Autenticación de llave pública: 'ssh/authKey.md'
- Resolución de nombres: 
    - El archivo hosts: 'dns/archivoHosts.md'
    - ¿Qué es el DNS?: 'dns/index.md'
    - BIND: 
        - Introducción: 'dns/bind.md'
        - Instalación: 'dns/instalacion.md'
        - DNS caché: 'dns/cache.md'
        - DNS local: 
            - Zona de autoridad: 'dns/zonas.md'
            - Resolución directa: 'dns/resolvd.md'
            - Resolución inversa: 'dns/resolvi.md'
            - Configurando el resolver: 'dns/resolver.md'
        - Configurando clientes: 'dns/clientes.md'
        - Realizando pruebas: 'dns/test.md'
- LAMP:
    - ¿Qué es LAMP?: 'lamp/queEs.md'
    - Instalación: 'lamp/instalacion.md'
    - Gestión básica: 'lamp/gestionBasica.md'
    - Web de usuario: 'lamp/userdir.md'
    - Hosts virtuales: 'lamp/virtualHosts.md'
#    - WebDav: 'lamp/webDav.md'
    - Ejercicios: 'lamp/ejercicios.md'
- Samba:
    - ¿Qué es SAMBA?: 'samba/index.md'
    - Instalación: 'samba/instalacion.md'
    - Configuración general: 'samba/configuracionGeneral.md'
    - Gestión de usuarios: 'samba/gestionUsuarios.md'
    - Carpeta de usuario: 'samba/comparticionUsuario.md'
    - Carpeta de grupo: 'samba/comparticionGrupo.md'
    - Carpeta de invitados: 'samba/comparticionInvitados.md'
    - Clientes Windows: 'samba/clientesWindows.md'
    - Ejercicios: 'samba/ejercicios.md'
- Icecast:
    - ¿Qué es Icecast?: 'icecast/index.md'
    - Instalación: 'icecast/instalacion.md'
    - Inicializando el servidor: 'icecast/inicializacion.md'
    - Configuración general: 'icecast/configuracionGeneral.md'
    - Broadcasting: 'icecast/broadcasting.md'
    - Administración: 'icecast/administracion.md'
- Git:
    - ¿Qué es Git?: 'git/index.md'
    - Entornos distribuidos: 'git/flujoEntornosDistribuidos.md'
    - Instalación de Git: 'git/instalacion.md'
    - Configuración inicial: 'git/configuracionInicial.md'
    - Los tres estados: 'git/losTresEstados.md'
    - Inicializando repositorio local: 'git/repositorioLocal.md'
    - Git en el servidor: 'git/servidorGit.md'
    - Trabajando con remotos: 'git/trabajandoConRemotos.md'
    - Ramas: 'git/ramas.md'
    - Deshaciendo cambios: 'git/deshaciendoCambios.md'
    - Etiquetado: 'git/etiquetas.md'
    - Otros comandos: 'git/otrosComandosGit.md'
    - Ejemplo de uso de git: 'git/ejemploGit.md'
- Nagios:
    - ¿Qué es Nagios?: 'nagios/index.md'
    - Instalación: 'nagios/instalacion.md'
    - Configuración inicial: 'nagios/configuracion.md'
    - Definiendo equipos: 'nagios/equipos.md'
    - Definiendo grupos: 'nagios/grupos.md'
    - Definiendo servicios: 'nagios/servicios.md'
    - Agente Windows: 'nagios/nsclient.md'
    - Definiendo íconos: 'nagios/iconos.md'
    - Recursos adicionales: 'nagios/recursos.md'
- Proxy: 
    - Instrucciones: 'proxy/index.md'
